export const LANDING = {
  TEST_ID: {
    CONTAINER: 'LANDING_CONTAINER',
    FORM: 'LANDING_FORM',
    FORM_DESCRIPTION: 'LANDING_FORM_DESCRIPTION',
    FORM_HINT: 'LANDING_FORM_HINT',
    INPUT_TEXT: 'LANDING_INPUT_TEXT',
    LABEL_CHECKBOX: 'LANDING_LABEL_CHECKBOX',
    INPUT_CHECKBOX: 'LANDING_INPUT_CHECKBOX',
    SUBMIT_BUTTON: 'LANDING_SUBMIT_BUTTON',
    LANDING_IMAGE: 'LANDING_LANDING_IMAGE',
  },
};
